// UI copy for the /create prototype. EN + LT only for now.

export const STEPS = ['idea', 'clarify', 'deck', 'play'];

export const CREATE_STRINGS = {
  en: {
    steps: { idea: 'Idea', clarify: 'Refine', deck: 'Deck', play: 'Play' },
    back: 'Back',
    next: 'Next',
    // 1 · idea
    ideaTitle: 'What’s the occasion?',
    ideaHint: 'Describe who’s playing and why. The more detail, the better the cards.',
    ideaPlaceholder: 'e.g. My mom turns 60. Family dinner, 12 people, three generations at the table…',
    examples: 'Try an example',
    deckLang: 'Card language',
    otherLang: 'Other…',
    otherLangPlaceholder: 'Type a language, e.g. Norwegian',
    cardCount: 'Cards',
    cards: 'cards',
    makeIt: 'Refine my idea',
    // 2 · clarify
    thinking: 'Tralala is thinking…',
    thinkingSub: 'Tralala is reading your idea and picking the questions that matter.',
    clarifyTitle: 'Let’s sharpen it',
    clarifyHint: 'Tralala tidied up your idea. Edit anything it got wrong, then answer a few quick ones.',
    refined: 'Your idea, refined',
    buildDeck: 'Write my cards',
    adultTitle: '18+ cards?',
    adultNote: 'Allow bold questions about sex. The word is never written: cards say *flamingo* instead.',
    adultNo: 'No',
    adultYes: 'Yes, 18+',
    // 3 · deck
    writing: 'Tralala is writing your cards…',
    writingSub: 'Tralala drafts the cards, then checks each one against its house rules.',
    deckTitle: 'Your deck',
    deckHint: 'Drag to reorder, ↻ to swap a card, ✕ to drop it.',
    deckEditHint: 'Drag to reorder, ✕ to drop a card.',
    deckName: 'Deck name',
    dragTip: 'Drag a card by ⋮⋮ to move it',
    gotIt: 'Got it',
    swap: 'Swap card',
    remove: 'Remove card',
    move: 'Drag to move',
    sampleNote: (n, total) => `Prototype shows ${n} sample cards. The real one writes all ${total}.`,
    langNote: (l) => `Prototype cards are in English. The real one writes in ${l}.`,
    save: 'Save & play',
    // 4 · play
    playHint: 'Your deck is saved. Tap or swipe the card, or use the arrows.',
    flamingoIntro: 'Before you start: in this deck, *flamingo* means sex. Swipe to begin.',
    of: 'of',
    prevCard: 'Previous card',
    nextCard: 'Next card',
    again: 'Start over',
    edit: 'Edit deck',
    newDeck: 'Make another deck',
    myDecks: 'My decks',
    savedLocal: 'Saved in this browser only',
    cardsCount: (n) => `${n} cards`,
    open: 'Play',
    nowPlaying: 'Playing',
    prototype: 'PROTOTYPE',
    modeMock: 'Sample data, free',
    modeAi: 'Real AI, costs money',
    writingWait: 'A big deck can take up to a minute.',
    writingPrep: 'Tralala is weighing ideas and picking the best. Cards start appearing in a moment.',
    prepLines: [
      'Reading your answers…',
      'Sketching twice as many ideas as needed…',
      'Dropping the generic ones…',
      'Making sure no two cards tell the same story…',
      'Keeping each card short enough to read aloud…',
      'Ordering them so the game warms up slowly…',
    ],
    writingLive: 'Cards appear as they’re written. You can edit them when it’s done.',
    writingCount: (n, t) => `${n} of ${t} cards written`,
    writingBtn: (n, t) => `Writing… ${n}/${t}`,
    stopWriting: 'Stop writing? The cards written so far are saved in My decks, but this still uses one deck from your code.',
    errorTitle: 'That didn’t work',
    errorGeneric: 'Something went wrong. Try again.',
    dismiss: 'Dismiss',
    // promo code
    codeTitle: 'Got a code?',
    codeHint: 'Making your own cards is open to people with a code for now. Type it in to start.',
    codeLabel: 'Code',
    codeGo: 'Start',
    codeChecking: 'Checking…',
    codeNote: 'The code stays in this browser, so you only type it once.',
    decksLeft: (n) => (n === 1 ? '1 deck left' : `${n} decks left`),
    until: (d) => `until ${d}`,
    otherCode: 'Use another code',
    usedUpNote: 'This code has no decks left. You can still play and edit the decks you saved.',
    swapsLeft: (n) => `${n} swaps left for this deck`,
    codeErrors: {
      code_bad: 'That code doesn’t exist. Check it and try again.',
      locked: 'Too many wrong codes. Try again in 15 minutes.',
      code_expired: 'This code has expired.',
      code_off: 'This code was switched off.',
      code_used_up: 'This code has no decks left.',
      clarify_used_up: 'This code has asked for too many refinements. Write the deck with what you have.',
      swaps_used_up: 'No more swaps for this deck.',
      daily_limit: 'Tralala has written a lot of cards today. Try again tomorrow.',
      connection_lost: 'The connection dropped. Keep the screen on and try again.',
    },
  },
  lt: {
    steps: { idea: 'Idėja', clarify: 'Tikslinimas', deck: 'Kaladė', play: 'Žaisk' },
    back: 'Atgal',
    next: 'Toliau',
    ideaTitle: 'Kokia proga?',
    ideaHint: 'Parašyk, kas žais ir kodėl. Kuo daugiau detalių, tuo geresnės kortos.',
    ideaPlaceholder: 'Pvz.: mamai 60. Šeimos vakarienė, 12 žmonių, trys kartos prie stalo…',
    examples: 'Išbandyk pavyzdį',
    deckLang: 'Kortų kalba',
    otherLang: 'Kita…',
    otherLangPlaceholder: 'Įrašyk kalbą, pvz. norvegų',
    cardCount: 'Kortų',
    cards: 'kortų',
    makeIt: 'Patobulinti idėją',
    thinking: 'Tralala galvoja…',
    thinkingSub: 'Tralala skaito tavo idėją ir renkasi svarbiausius klausimus.',
    clarifyTitle: 'Patikslinkime',
    clarifyHint: 'Tralala sutvarkė tavo idėją. Pataisyk, jei kažką suprato ne taip, ir atsakyk į kelis klausimus.',
    refined: 'Tavo idėja, patobulinta',
    buildDeck: 'Rašyti kortas',
    adultTitle: '18+ kortos?',
    adultNote: 'Leisti drąsius klausimus apie seksą. Pats žodis nerašomas: kortose vietoj jo bus *flamingas*.',
    adultNo: 'Ne',
    adultYes: 'Taip, 18+',
    writing: 'Tralala rašo tavo kortas…',
    writingSub: 'Tralala rašo kortas, tada kiekvieną tikrina pagal savo taisykles.',
    deckTitle: 'Tavo kaladė',
    deckHint: 'Tempk, kad perkeltum, ↻ pakeisk kortą, ✕ ištrink.',
    deckEditHint: 'Tempk, kad perkeltum, ✕ ištrink kortą.',
    deckName: 'Kaladės pavadinimas',
    dragTip: 'Tempk kortą už ⋮⋮, kad perkeltum',
    gotIt: 'Supratau',
    swap: 'Pakeisti kortą',
    remove: 'Ištrinti kortą',
    move: 'Tempk, kad perkeltum',
    sampleNote: (n, total) => `Prototipas rodo ${n} pavyzdines kortas. Tikras parašys visas ${total}.`,
    langNote: (l) => `Prototipo kortos angliškos. Tikras rašys kalba: ${l}.`,
    save: 'Išsaugoti ir žaisti',
    playHint: 'Kaladė išsaugota. Bakstelėk ar braukk kortą arba naudok rodykles.',
    flamingoIntro: 'Prieš pradedant: šioje kaladėje *flamingas* reiškia seksą. Braukk kortą ir pradėk.',
    of: 'iš',
    prevCard: 'Ankstesnė korta',
    nextCard: 'Kita korta',
    again: 'Iš naujo',
    edit: 'Redaguoti kaladę',
    newDeck: 'Kurti kitą kaladę',
    myDecks: 'Mano kaladės',
    savedLocal: 'Išsaugota tik šioje naršyklėje',
    cardsCount: (n) => `Kortų: ${n}`,
    open: 'Žaisti',
    nowPlaying: 'Žaidžiama',
    prototype: 'PROTOTIPAS',
    modeMock: 'Pavyzdiniai duomenys, nemokamai',
    modeAi: 'Tikras AI, kainuoja',
    writingWait: 'Didelė kaladė gali užtrukti iki minutės.',
    writingPrep: 'Tralala sveria idėjas ir renkasi geriausias. Kortos netrukus pradės rodytis.',
    prepLines: [
      'Skaito tavo atsakymus…',
      'Prirašo dvigubai daugiau idėjų, nei reikia…',
      'Išmeta banalias…',
      'Tikrina, kad dvi kortos nepasakotų tos pačios istorijos…',
      'Trumpina, kad būtų lengva perskaityti balsu…',
      'Dėlioja taip, kad žaidimas įsibėgėtų pamažu…',
    ],
    writingLive: 'Kortos atsiranda, kai tik parašomos. Redaguoti galėsi, kai baigsis.',
    writingCount: (n, t) => `Parašyta ${n} iš ${t}`,
    writingBtn: (n, t) => `Rašoma… ${n}/${t}`,
    stopWriting: 'Nutraukti rašymą? Jau parašytos kortos bus išsaugotos „Mano kaladėse“, bet iš kodo vis tiek bus nuskaičiuota viena kaladė.',
    errorTitle: 'Nepavyko',
    errorGeneric: 'Kažkas nepavyko. Bandyk dar kartą.',
    dismiss: 'Uždaryti',
    codeTitle: 'Turi kodą?',
    codeHint: 'Kol kas savo kortas kurti gali tik turintys kodą. Įvesk jį ir pradėk.',
    codeLabel: 'Kodas',
    codeGo: 'Pradėti',
    codeChecking: 'Tikrinama…',
    codeNote: 'Kodas lieka šioje naršyklėje, tad įvesti reikia tik kartą.',
    decksLeft: (n) => `Liko kaladžių: ${n}`,
    until: (d) => `iki ${d}`,
    otherCode: 'Kitas kodas',
    usedUpNote: 'Šiam kodui kaladžių neliko. Išsaugotas kalades vis tiek gali žaisti ir redaguoti.',
    swapsLeft: (n) => `Šiai kaladei liko keitimų: ${n}`,
    codeErrors: {
      code_bad: 'Tokio kodo nėra. Patikrink ir bandyk dar kartą.',
      locked: 'Per daug neteisingų kodų. Bandyk po 15 minučių.',
      code_expired: 'Šio kodo galiojimas baigėsi.',
      code_off: 'Šis kodas išjungtas.',
      code_used_up: 'Šiam kodui kaladžių neliko.',
      clarify_used_up: 'Šiuo kodu idėja tobulinta per daug kartų. Rašyk kaladę su tuo, ką turi.',
      swaps_used_up: 'Šiai kaladei keitimų nebeliko.',
      daily_limit: 'Tralala šiandien parašė daug kortų. Bandyk rytoj.',
      connection_lost: 'Nutrūko ryšys. Laikyk ekraną įjungtą ir bandyk dar kartą.',
    },
  },
};

// Deck languages offered up front; "Other…" accepts any language by name.
export const DECK_LANGS = [
  { code: 'en', name: { en: 'English', lt: 'Anglų' } },
  { code: 'lt', name: { en: 'Lithuanian', lt: 'Lietuvių' } },
  { code: 'de', name: { en: 'German', lt: 'Vokiečių' } },
  { code: 'es', name: { en: 'Spanish', lt: 'Ispanų' } },
  { code: 'it', name: { en: 'Italian', lt: 'Italų' } },
  { code: 'pl', name: { en: 'Polish', lt: 'Lenkų' } },
];
