// UI copy for the /create prototype. EN + LT only for now.

export const STEPS = ['idea', 'clarify', 'deck', 'play'];

export const CREATE_STRINGS = {
  en: {
    steps: { idea: 'Idea', clarify: 'Refine', deck: 'Deck', play: 'Play' },
    back: 'Back',
    next: 'Next',
    // 1 · idea
    ideaTitle: 'What’s the occasion?',
    ideaHint: 'Describe in your own words who’s playing and why. The more detail, the better the cards.',
    ideaPlaceholder: 'Who’s playing, and how many?\nWhat’s the occasion, and where?\nAny shared story or detail?\nWhat mood are you after?\nAnything to avoid?',
    examples: 'Try an example',
    deckLang: 'Card language',
    otherLang: 'Other…',
    otherLangPlaceholder: 'Type a language, e.g. Norwegian',
    cardCount: 'Cards',
    cards: 'cards',
    makeIt: 'Refine my idea',
    // 2 · clarify
    thinking: 'Tralala is thinking…',
    // Loading screen titles; they take turns every few seconds.
    thinkingLines: ['Tralala is reading your idea…', 'Hmm, interesting idea…', 'Tralala is getting into it…'],
    clarifyTitle: 'Let’s sharpen it',
    clarifyHint: 'Tralala tidied up your idea. Edit anything it got wrong, then answer a few quick ones.',
    refined: 'Your idea, refined',
    buildDeck: 'Write my cards',
    adultTitle: '18+ cards?',
    adultNote: 'Allow bold questions about sex. The word is never written: cards say *flamingo* instead.',
    adultNo: 'No',
    adultYes: 'Yes, 18+',
    // 3 · deck
    writing: 'Tralala is writing your cards…',
    writingLines: [
      'Tralala is finding the best questions.',
      'Building your own personal card collection.',
      'Boring questions out, only good ones stay.',
      'Checking every question is worth your night.',
      'Nobody else has a deck like this.',
      'Your one-of-a-kind deck is almost ready.',
    ],
    deckTitle: 'Your deck',
    deckHint: 'Drag to reorder, ↻ to swap a card, ✕ to drop it.',
    deckEditHint: 'Drag to reorder, ✕ to drop a card.',
    deckName: 'Deck name',
    dragTip: 'Drag a card by ⋮⋮ to move it',
    gotIt: 'Got it',
    swap: 'Swap card',
    remove: 'Remove card',
    move: 'Drag to move',
    sampleNote: (n, total) => `Prototype shows ${n} sample cards. The real one writes all ${total}.`,
    langNote: (l) => `Prototype cards are in English. The real one writes in ${l}.`,
    save: 'Save & play',
    // 4 · play
    play: 'Play',
    resume: (i, n) => `Continue · ${i} / ${n}`,
    fromStart: 'Start from the first card',
    showTv: 'Show on TV',
    onTv: 'On TV',
    next: 'Next',
    closePlay: 'Back to the deck',
    endTitle: 'That’s the deck',
    endHint: 'You’ve been through every card. Play it again, or pick another deck.',
    playAgain: 'Play again',
    toDeck: 'Back to deck',
    flamingoIntro: 'Before you start: in this deck, *flamingo* means sex. Swipe to begin.',
    of: 'of',
    prevCard: 'Previous card',
    nextCard: 'Next card',
    again: 'Start over',
    edit: 'Edit deck',
    newDeck: 'Make another deck',
    myDecks: 'My decks',
    savedLocal: 'Saved in this browser only',
    cardsCount: (n) => `${n} cards`,
    open: 'Play',
    nowPlaying: 'Playing',
    prototype: 'PROTOTYPE',
    modeMock: 'Sample data, free',
    modeAi: 'Real AI, costs money',
    writingWait: 'A big deck can take up to a minute. Perfect time to pour some tea.',
    writingPrep: 'Tralala is weighing ideas and picking the best. Cards start appearing in a moment.',
    prepLines: [
      'Reading your answers…',
      'Sketching twice as many ideas as needed…',
      'Dropping the generic ones…',
      'Making sure no two cards tell the same story…',
      'Keeping each card short enough to read aloud…',
      'Ordering them so the game warms up slowly…',
    ],
    writingLive: 'Cards appear as they’re written. You can edit them when it’s done.',
    writingCount: (n, t) => `${n} of ${t} cards written`,
    writingBtn: (n, t) => `Writing… ${n}/${t}`,
    stopWriting: 'Stop writing? The cards written so far are saved in My decks, but this still uses one deck from your code.',
    errorTitle: 'That didn’t work',
    errorGeneric: 'Something went wrong. Try again.',
    dismiss: 'Dismiss',
    // promo code
    codeTitle: 'Got a code?',
    codeHint: 'Making your own cards is open to people with a code for now. Type it in to start.',
    codeLabel: 'Code',
    codeGo: 'Start',
    codeChecking: 'Checking…',
    codeNote: 'The code stays in this browser, so you only type it once.',
    decksLeft: (n) => (n === 1 ? '1 deck left' : `${n} decks left`),
    until: (d) => `until ${d}`,
    otherCode: 'Use another code',
    usedUpNote: 'This code has no decks left. You can still play and edit the decks you saved.',
    swapsLeft: (n) => `${n} swaps left for this deck`,
    codeErrors: {
      code_bad: 'That code doesn’t exist. Check it and try again.',
      locked: 'Too many wrong codes. Try again in 15 minutes.',
      code_expired: 'This code has expired.',
      code_off: 'This code was switched off.',
      code_used_up: 'This code has no decks left.',
      clarify_used_up: 'This code has asked for too many refinements. Write the deck with what you have.',
      swaps_used_up: 'No more swaps for this deck.',
      daily_limit: 'Tralala has written a lot of cards today. Try again tomorrow.',
      connection_lost: 'The connection dropped. Keep the screen on and try again.',
    },
  },
  lt: {
    steps: { idea: 'Idėja', clarify: 'Tikslinimas', deck: 'Kaladė', play: 'Žaisk' },
    back: 'Atgal',
    next: 'Toliau',
    ideaTitle: 'Kokia proga?',
    ideaHint: 'Parašyk savais žodžiais, kas žais ir kodėl. Kuo daugiau detalių, tuo geresnės kortos.',
    ideaPlaceholder: 'Kas žais ir kiek jūsų?\nKokia proga ir kur?\nKokia bendra istorija ar detalė?\nKokios nuotaikos norisi?\nKo geriau vengti?',
    examples: 'Išbandyk pavyzdį',
    deckLang: 'Kortų kalba',
    otherLang: 'Kita…',
    otherLangPlaceholder: 'Įrašyk kalbą, pvz. norvegų',
    cardCount: 'Kortų',
    cards: 'kortų',
    makeIt: 'Patobulinti idėją',
    thinking: 'Tralala galvoja…',
    thinkingLines: ['Tralala skaito tavo idėją…', 'Hmm, įdomi mintis…', 'Tralala įsijaučia…'],
    clarifyTitle: 'Patikslinkime',
    clarifyHint: 'Tralala sutvarkė tavo idėją. Pataisyk, jei kažką suprato ne taip, ir atsakyk į kelis klausimus.',
    refined: 'Tavo idėja, patobulinta',
    buildDeck: 'Rašyti kortas',
    adultTitle: '18+ kortos?',
    adultNote: 'Leisti drąsius klausimus apie seksą. Pats žodis nerašomas: kortose vietoj jo bus *flamingas*.',
    adultNo: 'Ne',
    adultYes: 'Taip, 18+',
    writing: 'Tralala rašo tavo kortas…',
    writingLines: [
      'Tralala galvoja geriausius klausimus.',
      'Kuriama tavo asmeninė kortų kolekcija.',
      'Nuobodūs klausimai keliauja lauk, lieka tik geri.',
      'Tikrina, ar kiekvienas klausimas vertas jūsų vakaro.',
      'Tokios kaladės dar niekas neturi.',
      'Tuoj turėsi savo vienintelę kortų kaladę.',
    ],
    deckTitle: 'Tavo kaladė',
    deckHint: 'Tempk, kad perkeltum, ↻ pakeisk kortą, ✕ ištrink.',
    deckEditHint: 'Tempk, kad perkeltum, ✕ ištrink kortą.',
    deckName: 'Kaladės pavadinimas',
    dragTip: 'Tempk kortą už ⋮⋮, kad perkeltum',
    gotIt: 'Supratau',
    swap: 'Pakeisti kortą',
    remove: 'Ištrinti kortą',
    move: 'Tempk, kad perkeltum',
    sampleNote: (n, total) => `Prototipas rodo ${n} pavyzdines kortas. Tikras parašys visas ${total}.`,
    langNote: (l) => `Prototipo kortos angliškos. Tikras rašys kalba: ${l}.`,
    save: 'Išsaugoti ir žaisti',
    play: 'Žaisti',
    resume: (i, n) => `Tęsti · ${i} / ${n}`,
    fromStart: 'Pradėti nuo pirmos kortos',
    showTv: 'Rodyti per TV',
    onTv: 'Rodoma per TV',
    next: 'Toliau',
    closePlay: 'Atgal į kaladę',
    endTitle: 'Kaladė baigta',
    endHint: 'Perėjot visas kortas. Žaiskit dar kartą arba rinkitės kitą kaladę.',
    playAgain: 'Žaisti iš naujo',
    toDeck: 'Atgal į kaladę',
    flamingoIntro: 'Prieš pradedant: šioje kaladėje *flamingas* reiškia seksą. Braukk kortą ir pradėk.',
    of: 'iš',
    prevCard: 'Ankstesnė korta',
    nextCard: 'Kita korta',
    again: 'Iš naujo',
    edit: 'Redaguoti',
    newDeck: 'Kurti kitą kaladę',
    myDecks: 'Mano kaladės',
    savedLocal: 'Išsaugota tik šioje naršyklėje',
    cardsCount: (n) => `Kortų: ${n}`,
    open: 'Žaisti',
    nowPlaying: 'Žaidžiama',
    prototype: 'PROTOTIPAS',
    modeMock: 'Pavyzdiniai duomenys, nemokamai',
    modeAi: 'Tikras AI, kainuoja',
    writingWait: 'Didelė kaladė užtrunka iki minutės. Puikus metas įsipilti arbatos.',
    writingPrep: 'Tralala sveria idėjas ir renkasi geriausias. Kortos netrukus pradės rodytis.',
    prepLines: [
      'Skaito tavo atsakymus…',
      'Prirašo dvigubai daugiau idėjų, nei reikia…',
      'Išmeta banalias…',
      'Tikrina, kad dvi kortos nepasakotų tos pačios istorijos…',
      'Trumpina, kad būtų lengva perskaityti balsu…',
      'Dėlioja taip, kad žaidimas įsibėgėtų pamažu…',
    ],
    writingLive: 'Kortos atsiranda, kai tik parašomos. Redaguoti galėsi, kai baigsis.',
    writingCount: (n, t) => `Parašyta ${n} iš ${t}`,
    writingBtn: (n, t) => `Rašoma… ${n}/${t}`,
    stopWriting: 'Nutraukti rašymą? Jau parašytos kortos bus išsaugotos „Mano kaladėse“, bet iš kodo vis tiek bus nuskaičiuota viena kaladė.',
    errorTitle: 'Nepavyko',
    errorGeneric: 'Kažkas nepavyko. Bandyk dar kartą.',
    dismiss: 'Uždaryti',
    codeTitle: 'Turi kodą?',
    codeHint: 'Kol kas savo kortas kurti gali tik turintys kodą. Įvesk jį ir pradėk.',
    codeLabel: 'Kodas',
    codeGo: 'Pradėti',
    codeChecking: 'Tikrinama…',
    codeNote: 'Kodas lieka šioje naršyklėje, tad įvesti reikia tik kartą.',
    decksLeft: (n) => `Liko kaladžių: ${n}`,
    until: (d) => `iki ${d}`,
    otherCode: 'Kitas kodas',
    usedUpNote: 'Šiam kodui kaladžių neliko. Išsaugotas kalades vis tiek gali žaisti ir redaguoti.',
    swapsLeft: (n) => `Šiai kaladei liko keitimų: ${n}`,
    codeErrors: {
      code_bad: 'Tokio kodo nėra. Patikrink ir bandyk dar kartą.',
      locked: 'Per daug neteisingų kodų. Bandyk po 15 minučių.',
      code_expired: 'Šio kodo galiojimas baigėsi.',
      code_off: 'Šis kodas išjungtas.',
      code_used_up: 'Šiam kodui kaladžių neliko.',
      clarify_used_up: 'Šiuo kodu idėja tobulinta per daug kartų. Rašyk kaladę su tuo, ką turi.',
      swaps_used_up: 'Šiai kaladei keitimų nebeliko.',
      daily_limit: 'Tralala šiandien parašė daug kortų. Bandyk rytoj.',
      connection_lost: 'Nutrūko ryšys. Laikyk ekraną įjungtą ir bandyk dar kartą.',
    },
  },
};

// Deck languages offered up front; "Other…" accepts any language by name.
// Example ideas on the Idea screen. Each one shows the shape of a good idea:
// who's playing, the occasion, a concrete detail, the mood, what to avoid.
// First date shares its text with the mock set of the same id (mockData.js),
// so the owner's Mock mode still finds it; the others fall back to the
// friends mock set.
export const IDEA_EXAMPLES = [
  {
    id: 'fanNight',
    chip: { en: '🎬 Fan night', lt: '🎬 Fanų vakaras' },
    prompt: {
      en: 'Six friends since college. We’re watching our favorite show’s finale at my place. We’ve all seen every season more than once and have our favorite characters and old arguments. Lots of laughs and hot takes. Nobody has seen the finale yet, so no spoilers.',
      lt: 'Šeši draugai nuo studijų. Susirenkam pas mane žiūrėti mėgstamo serialo finalo. Visus sezonus matėm po kelis kartus, turim savo mėgstamus veikėjus ir senų ginčų. Norisi daug juoko ir karštų nuomonių. Finalo dar niekas nematė, tad be spoilerių.',
    },
  },
  {
    id: 'dateNight',
    chip: { en: '❤️ Date night', lt: '❤️ Porų vakaras' },
    prompt: {
      en: 'Just the two of us, together 7 years, two kids. Finally a night without them: dinner at home. We want to laugh, remember how we met and learn something new about each other. It can go deeper, but no boring questions about chores.',
      lt: 'Mes dviese, kartu 7 metai, du vaikai. Pagaliau vakaras be jų: vakarienė namie. Norim pasijuokti, prisiminti, kaip susipažinom, ir sužinoti vienas apie kitą ką nors naujo. Galima ir giliau, bet be banalių klausimų apie buitį.',
    },
  },
  {
    id: 'firstDate',
    chip: { en: '💑 First date', lt: '💑 Pirmas pasimatymas' },
    prompt: {
      en: 'First date with someone from a dating app, we’ve only texted so far. We’re both around 30. Coffee, then a walk. Light and curious so the conversation keeps going, with a little flirting.',
      lt: 'Pirmas pasimatymas su žmogumi iš pažinčių programėlės, iki šiol tik susirašinėjom. Abiem apie 30. Kava, paskui pasivaikščiojimas. Lengvai ir smalsiai, kad pokalbis nenutrūktų, su trupučiu flirto.',
    },
  },
  {
    id: 'icebreaker',
    chip: { en: '🧊 Icebreaker', lt: '🧊 Susipažinimas' },
    prompt: {
      en: 'About 10 neighbors from a new apartment building, we barely know each other. Our first evening together, at the grill in the yard. Ages 25 to 70. Light and fun so everyone talks, even the shy ones. Nothing too personal.',
      lt: 'Apie 10 kaimynų iš naujo daugiabučio, beveik nepažįstam vienas kito. Pirmas bendras vakaras kieme prie grilio. Amžius nuo 25 iki 70. Lengvai ir smagiai, kad prakalbėtų visi, net drovesni. Nieko per asmeniško.',
    },
  },
  {
    id: 'bachelorette',
    chip: { en: '👰 Bachelorette', lt: '👰 Mergvakaris' },
    prompt: {
      en: '8 friends, Emma’s bachelorette. Some know her from school, some from work, a few have never met. A weekend at a country house. Bold and fun: stories about Emma, her fiancé Jake and our own adventures. Nothing about exes.',
      lt: '8 draugės, Gintarės mergvakaris. Vienos ją pažįsta nuo mokyklos, kitos iš darbo, kai kurios viena kitos dar nematė. Savaitgalis sodyboje. Drąsiai ir linksmai: istorijos apie Gintarę, jos sužadėtinį Marių ir mūsų nuotykius. Nieko apie buvusius.',
    },
  },
];

export const DECK_LANGS = [
  { code: 'en', name: { en: 'English', lt: 'Anglų' } },
  { code: 'lt', name: { en: 'Lithuanian', lt: 'Lietuvių' } },
  { code: 'de', name: { en: 'German', lt: 'Vokiečių' } },
  { code: 'es', name: { en: 'Spanish', lt: 'Ispanų' } },
  { code: 'it', name: { en: 'Italian', lt: 'Italų' } },
  { code: 'pl', name: { en: 'Polish', lt: 'Lenkų' } },
];
