// Trala.la — all content lives here.
// Add a question: append a row to QUESTIONS. Add a category: add to CATEGORIES
// (id, en, lt, icon) and a hue in CATEGORY_TINT, then write its questions.
// Row format: [categoryId, English, Lithuanian, likeRate]

const CATS = [
  { id: 'fun',    en: 'Fun', lt: 'Linksmi', icon: '🎉' },
  { id: 'know',   en: 'Know me', lt: 'Pažink mane', icon: '🙂' },
  { id: 'deep',   en: 'Deep', lt: 'Gilūs', icon: '🌊' },
  { id: 'team',   en: 'Team', lt: 'Komanda', icon: '🤝' },
  { id: 'spicy',  en: 'Spicy', lt: 'Aštrūs', icon: '🌶', note: '18+' },
  { id: 'future', en: 'Future', lt: 'Ateitis', icon: '🔮' },
  { id: 'firsts', en: 'Firsts', lt: 'Pirmi kartai', icon: '🎬' },
  { id: 'awkward',en: 'Awkward', lt: 'Nejaukūs', icon: '😅' },
  { id: 'couples',en: 'Couples', lt: 'Poroms', icon: '💛' },
  { id: 'food',   en: 'Food', lt: 'Maistas', icon: '🍜' },
];

const Q = [
  ['fun', 'What\'s the most useless talent you\'re weirdly proud of?', 'Koks nenaudingiausias talentas, kuriuo keistai didžiuojiesi?', 58],
  ['fun', 'If you had a theme song that played every time you walked into a room, what would it be?', 'Jei kiekvieną kartą įžengus į kambarį grotų tavo daina — kokia ji būtų?', 64],
  ['fun', 'What\'s the most impulsive purchase you\'ve ever made?', 'Koks impulsyviausias tavo pirkinys?', 47],
  ['fun', 'Who here would survive longest in a zombie apocalypse, and why?', 'Kas čia ilgiausiai išgyventų zombių apokalipsėje ir kodėl?', 71],
  ['fun', 'What\'s the worst haircut you\'ve ever had?', 'Kokia blogiausia tavo šukuosena?', 52],
  ['fun', 'If this group started a band tomorrow, what would we be called?', 'Jei rytoj įkurtume grupę — kaip vadintumėmės?', 69],
  ['fun', 'What\'s a completely useless fact you know by heart?', 'Kokį visiškai nenaudingą faktą moki atmintinai?', 44],
  ['fun', 'What\'s the weirdest thing you\'ve ever eaten on a dare?', 'Keisčiausias dalykas, kurį suvalgei iš drąsos?', 41],
  ['fun', 'If you could instantly swap lives with someone in this room for a day, who would it be?', 'Jei dienai galėtum apsikeisti gyvenimais su kuo nors čia — su kuo?', 66],
  ['fun', 'What\'s a rule you make everyone follow when they\'re at your place?', 'Kokią taisyklę verti visus laikytis pas tave namuose?', 39],
  ['fun', 'What\'s the most ridiculous thing you\'ve ever Googled?', 'Juokingiausias dalykas, kurio ieškojai Google?', 55],
  ['fun', 'If the group had a mascot, what animal would it be?', 'Jei grupė turėtų talismaną — koks gyvūnas tai būtų?', 48],
  ['fun', 'What\'s a trend you fully participated in and now regret?', 'Kokioje madoje dalyvavai iš visų jėgų ir dabar gailiesi?', 57],
  ['fun', 'What\'s the strangest compliment you\'ve ever received?', 'Keisčiausias komplimentas, kokį esi gavęs?', 50],
  ['fun', 'If you had to be known for one weird party trick forever, what would you pick?', 'Jei amžinai būtum žinomas dėl vieno keisto triuko — kokio?', 43],
  ['know', 'What\'s a small habit of yours that most people don\'t know about?', 'Koks tavo mažas įprotis, apie kurį dauguma nežino?', 62],
  ['know', 'What\'s the last book, show, or song that genuinely changed how you think?', 'Kokia paskutinė knyga, serialas ar daina tikrai pakeitė tavo mąstymą?', 68],
  ['know', 'What\'s something you believed as a kid that turned out to be completely wrong?', 'Kuo tikėjai vaikystėje, kas pasirodė visiška netiesa?', 59],
  ['know', 'What\'s a skill you wish you\'d learned earlier in life?', 'Kokio įgūdžio norėtum, kad būtum išmokęs anksčiau?', 53],
  ['know', 'What\'s the best piece of advice you\'ve ever actually followed?', 'Koks geriausias patarimas, kurio tikrai paklausei?', 61],
  ['know', 'What\'s something about you that surprises people once they get to know you?', 'Kas tavyje nustebina žmones, kai tave pažįsta geriau?', 70],
  ['know', 'What\'s a place that shaped who you are more than you expected?', 'Kokia vieta tave suformavo labiau, nei tikėjaisi?', 56],
  ['know', 'What\'s a value you hold that you didn\'t inherit from your family?', 'Kokią vertybę turi, kurios nepaveldėjai iš šeimos?', 64],
  ['know', 'What\'s something you\'re better at than almost anyone else you know?', 'Ką moki geriau nei beveik visi, kuriuos pažįsti?', 73],
  ['know', 'What\'s a decision you made that quietly changed the direction of your life?', 'Koks sprendimas tyliai pakeitė tavo gyvenimo kryptį?', 79],
  ['know', 'What\'s something you do differently now than you did five years ago?', 'Ką dabar darai kitaip nei prieš penkerius metus?', 51],
  ['know', 'What\'s a question you wish people asked you more often?', 'Kokio klausimo norėtum, kad tavęs dažniau klaustų?', 75],
  ['know', 'What\'s a part of your personality you had to work hard to build?', 'Kurią savo asmenybės dalį teko sunkiai išsiugdyti?', 66],
  ['know', 'Who in your life sees a version of you that most people don\'t?', 'Kas tavo gyvenime mato tokį tave, kokio kiti nemato?', 72],
  ['know', 'What\'s something small that always tells you a lot about a person?', 'Kokia smulkmena visada daug pasako apie žmogų?', 60],
  ['deep', 'What\'s something you\'re avoiding right now that you know you need to face?', 'Ko dabar vengi, nors žinai, kad reikia susidurti?', 86],
  ['deep', 'What\'s a belief you held strongly that you\'ve since let go of?', 'Kokio įsitikinimo tvirtai laikeisi ir vėliau paleidai?', 71],
  ['deep', 'What\'s the hardest truth you\'ve ever had to accept about yourself?', 'Kokią sunkiausią tiesą apie save teko priimti?', 83],
  ['deep', 'What\'s something you\'ve never told anyone in this room?', 'Ko niekada nesakei niekam šiame kambaryje?', 88],
  ['deep', 'What\'s a regret you\'ve made peace with, and how did you get there?', 'Su kokia gaila susitaikei ir kaip tai pavyko?', 74],
  ['deep', 'What\'s something you forgive yourself for now that you didn\'t used to?', 'Ką sau dabar atleidi, ko anksčiau neatleisdavai?', 69],
  ['deep', 'What does it look like when you\'re truly happy, not just okay?', 'Kaip atrodo, kai esi tikrai laimingas, o ne tiesiog gerai?', 77],
  ['deep', 'What\'s a fear that quietly shapes more of your decisions than you\'d like to admit?', 'Kokia baimė tyliai lemia daugiau tavo sprendimų, nei norėtum pripažinti?', 81],
  ['deep', 'What\'s something you needed to hear when you were younger that no one said?', 'Ką tau reikėjo išgirsti jaunystėje, bet niekas nepasakė?', 85],
  ['deep', 'What\'s a relationship that taught you something you couldn\'t have learned any other way?', 'Kokie santykiai išmokė to, ko kitaip nebūtum išmokęs?', 70],
  ['deep', 'What would you want people to remember about how you made them feel?', 'Ką norėtum, kad žmonės prisimintų apie tai, kaip su tavimi jautėsi?', 78],
  ['deep', 'What\'s something you\'re proud of that no one ever congratulated you for?', 'Kuo didžiuojiesi, nors niekas tavęs už tai nepasveikino?', 80],
  ['deep', 'What\'s a version of yourself you\'re still trying to become?', 'Kokiu savimi vis dar bandai tapti?', 73],
  ['deep', 'What\'s the closest you\'ve come to giving up on something that mattered?', 'Kada buvai arčiausiai to, kad pasiduotum dėl kažko svarbaus?', 67],
  ['deep', 'What\'s something you\'re carrying that you\'ve never fully put down?', 'Ką neši su savimi ir niekada iki galo nepadėjai?', 84],
  ['team', 'What\'s something someone did for you at work that you never forgot?', 'Ką kas nors padarė dėl tavęs darbe, ko niekada nepamiršai?', 68],
  ['team', 'What does it look like when this team is at its best?', 'Kaip atrodo ši komanda, kai jai geriausiai sekasi?', 61],
  ['team', 'What\'s a piece of feedback that changed how you work?', 'Koks atsiliepimas pakeitė tavo darbo būdą?', 65],
  ['team', 'What do you need from the people around you when things get stressful?', 'Ko tau reikia iš aplinkinių, kai darosi įtempta?', 79],
  ['team', 'What\'s a mistake you made early in your career that taught you the most?', 'Kokia klaida karjeros pradžioje išmokė daugiausiai?', 58],
  ['team', 'What\'s something you wish more people asked you about your work?', 'Ko norėtum, kad daugiau žmonių tavęs klaustų apie darbą?', 63],
  ['team', 'Who on this team do you learn the most from, and why?', 'Iš ko šioje komandoje mokaisi daugiausiai ir kodėl?', 70],
  ['team', 'What\'s a moment you felt truly proud to be part of this group?', 'Kada tikrai didžiavaisi, kad esi šios komandos dalis?', 64],
  ['team', 'What\'s something small this team could do that would make a big difference?', 'Kokia smulkmena šioje komandoje pakeistų labai daug?', 72],
  ['team', 'What\'s a strength you have that this team doesn\'t fully use yet?', 'Kokios tavo stiprybės komanda dar neišnaudoja?', 76],
  ['team', 'What kind of recognition actually matters to you at work?', 'Koks pripažinimas darbe tau iš tikrųjų svarbus?', 67],
  ['team', 'What\'s a project or moment that reminded you why you do this work?', 'Koks projektas ar akimirka priminė, kodėl dirbi šį darbą?', 59],
  ['team', 'What\'s something you assume people know about you at work that they might not?', 'Ką manai, kad kolegos apie tave žino, o gal ir ne?', 62],
  ['team', 'What builds trust for you faster than almost anything else?', 'Kas tau greičiausiai sukuria pasitikėjimą?', 71],
  ['team', 'What\'s one thing you\'d change about how this team works together?', 'Ką vieną pakeistum, kaip ši komanda dirba kartu?', 74],
  ['spicy', 'What\'s something you\'ve done that you\'d never admit to your parents?', 'Ką esi padaręs, ko niekada neprisipažintum tėvams?', 82],
  ['spicy', 'Have you ever been in love with two people at the same time?', 'Ar kada mylėjai du žmones vienu metu?', 79],
  ['spicy', 'What\'s the boldest thing you\'ve ever done to get someone\'s attention?', 'Drąsiausias dalykas, kurį padarei, kad atkreiptum kažkieno dėmesį?', 68],
  ['spicy', 'What\'s a secret you\'ve kept that still weighs on you?', 'Kokia paslaptis vis dar tave slegia?', 84],
  ['spicy', 'Have you ever pretended to be someone you\'re not to impress someone?', 'Ar apsimetei kitu žmogumi, kad ką nors sužavėtum?', 66],
  ['spicy', 'What\'s the closest you\'ve come to a real scandal?', 'Kada buvai arčiausiai tikro skandalo?', 61],
  ['spicy', 'What\'s something you regret least, even though you probably should?', 'Ko mažiausiai gailiesi, nors turbūt turėtum?', 70],
  ['spicy', 'Have you ever ended a relationship for a reason you never explained?', 'Ar nutraukei santykius dėl priežasties, kurios niekada nepaaiškinai?', 75],
  ['spicy', 'What\'s the most reckless thing you\'ve done for love?', 'Beprotiškiausias dalykas, kurį padarei dėl meilės?', 73],
  ['spicy', 'What\'s a lie you told that you never got caught for?', 'Koks melas praėjo nepastebėtas?', 69],
  ['spicy', 'Have you ever wanted something you knew you shouldn\'t?', 'Ar kada norėjai to, ko žinojai, kad neturėtum?', 77],
  ['spicy', 'What\'s the most jealous you\'ve ever felt, and why?', 'Kada pavydėjai labiausiai ir kodėl?', 64],
  ['spicy', 'What\'s a line you swore you\'d never cross, and did you?', 'Kokią ribą prisiekei niekada neperžengti — ir ar peržengei?', 80],
  ['spicy', 'What\'s something you\'ve done that surprised even you?', 'Ką padarei, kas nustebino net tave patį?', 58],
  ['spicy', 'Who from your past do you think about more than you\'d admit?', 'Apie ką iš praeities galvoji dažniau, nei prisipažintum?', 86],
  ['future', 'What\'s something you want to be true about your life in ten years?', 'Kas po dešimties metų turėtų būti tiesa apie tavo gyvenimą?', 74],
  ['future', 'What\'s a risk you\'re thinking about taking but haven\'t yet?', 'Kokią riziką svarstai, bet dar nesiryžai?', 78],
  ['future', 'What\'s a version of success that matters to you, even if no one else would call it that?', 'Kokia sėkmė tau svarbi, net jei kiti jos taip nevadintų?', 81],
  ['future', 'What\'s something you hope you never stop doing?', 'Ko tikiesi niekada nenustoti daryti?', 62],
  ['future', 'What\'s a place you haven\'t been that you can already picture yourself in?', 'Kokioje vietoje dar nebuvai, bet jau save ten matai?', 57],
  ['future', 'What\'s a skill you want to master before you die?', 'Kokį įgūdį nori įvaldyti prieš mirtį?', 60],
  ['future', 'What do you hope people say about you when you\'re not in the room?', 'Ką tikiesi, kad žmonės sako apie tave, kai tavęs nėra?', 76],
  ['future', 'What\'s a dream you\'ve quietly downsized, and do you want it back?', 'Kokią svajonę tyliai sumažinai — ar nori jos atgal?', 83],
  ['future', 'What would you do differently if you knew you couldn\'t fail?', 'Ką darytum kitaip, jei žinotum, kad nepavykti negali?', 71],
  ['future', 'What\'s something you want to build, create, or start someday?', 'Ką nori kada nors sukurti, pastatyti ar pradėti?', 65],
  ['future', 'What\'s a habit you\'re trying to become the kind of person who has?', 'Kokį įprotį bandai išsiugdyti, kad taptum tokiu žmogumi?', 59],
  ['future', 'What does your ideal ordinary day look like ten years from now?', 'Kaip po dešimties metų atrodo tavo ideali eilinė diena?', 68],
  ['future', 'What\'s something you hope to teach someone one day?', 'Ko tikiesi kada nors ką nors išmokyti?', 55],
  ['future', 'What\'s a goal you\'ve never said out loud until now?', 'Koks tikslas, kurio niekada nesakei balsu iki šiol?', 79],
  ['future', 'What legacy do you want to leave, even in a small way?', 'Kokį pėdsaką nori palikti, kad ir mažą?', 66],
  ['firsts', 'What was your first job, and what did it teach you?', 'Koks buvo tavo pirmas darbas ir ko jis išmokė?', 56],
  ['firsts', 'What\'s the first thing you remember saving up for?', 'Ką pirmiausia prisimeni, kad taupei?', 48],
  ['firsts', 'What was the first real risk you ever took?', 'Kokia buvo pirmoji tikra rizika tavo gyvenime?', 63],
  ['firsts', 'What was your first heartbreak, and what did it teach you?', 'Koks buvo pirmas širdies skausmas ir ko jis išmokė?', 77],
  ['firsts', 'What\'s the first time you remember standing up for yourself?', 'Kada pirmą kartą prisimeni apgynęs save?', 69],
  ['firsts', 'What was the first big mistake you made that you learned the most from?', 'Kokia pirma didelė klaida išmokė daugiausiai?', 61],
  ['firsts', 'What\'s the first trip you took without your family?', 'Kokia pirmoji kelionė be šeimos?', 52],
  ['firsts', 'What was the first moment you felt truly proud of yourself?', 'Kada pirmą kartą tikrai savimi didžiavaisi?', 70],
  ['firsts', 'What\'s the first rule you ever broke on purpose?', 'Kokią taisyklę pirmą kartą sulaužei tyčia?', 54],
  ['firsts', 'What was your first impression of someone in this room, and has it changed?', 'Koks buvo pirmas įspūdis apie ką nors čia — ar jis pasikeitė?', 80],
  ['firsts', 'What\'s the first time you realized your parents were just people?', 'Kada supratai, kad tėvai — tiesiog žmonės?', 84],
  ['firsts', 'What was the first thing you ever built, made, or created that you were proud of?', 'Koks pirmas dalykas, kurį sukūrei ir kuriuo didžiavaisi?', 50],
  ['firsts', 'What\'s the first concert, game, or show that made you feel something?', 'Koks pirmas koncertas, žaidimas ar spektaklis tave sujaudino?', 45],
  ['firsts', 'What was the first time you had to make a big decision completely on your own?', 'Kada pirmą kartą teko priimti didelį sprendimą visiškai vienam?', 67],
  ['firsts', 'What\'s the first compliment you remember that actually stuck with you?', 'Koks pirmas komplimentas tau tikrai įstrigo?', 58],
  ['awkward', 'What\'s the most awkward thing that\'s ever happened to you in public?', 'Nejaukiausias dalykas, nutikęs tau viešumoje?', 72],
  ['awkward', 'What\'s a time you said “you too” when you really shouldn\'t have?', 'Kada pasakei „tau irgi“, kai tikrai neturėjai?', 81],
  ['awkward', 'What\'s the most embarrassing thing you\'ve done to get out of a conversation?', 'Gėdingiausias būdas, kuriuo išsisukai iš pokalbio?', 66],
  ['awkward', 'What\'s a time your body betrayed you at the worst possible moment?', 'Kada kūnas tave išdavė blogiausiu įmanomu metu?', 70],
  ['awkward', 'What\'s the most awkward first date you\'ve ever been on?', 'Nejaukiausias pirmas pasimatymas?', 75],
  ['awkward', 'What\'s something embarrassing you did that you thought no one noticed, but they did?', 'Ką gėdingo padarei manydamas, kad niekas nepastebėjo — o pastebėjo?', 68],
  ['awkward', 'What\'s the most cringe-worthy thing you\'ve ever posted online?', 'Gėdingiausias dalykas, kurį paskelbei internete?', 64],
  ['awkward', 'What\'s a time you completely misread a social situation?', 'Kada visiškai neteisingai supratai situaciją?', 59],
  ['awkward', 'What\'s the most awkward silence you\'ve ever sat through?', 'Nejaukiausia tyla, kurią teko iškentėti?', 61],
  ['awkward', 'What\'s a time you got caught doing something you shouldn\'t have?', 'Kada tave pagavo darant tai, ko neturėjai?', 67],
  ['awkward', 'What\'s the worst case of mistaken identity you\'ve ever had?', 'Blogiausias atvejis, kai tave supainiojo su kitu?', 53],
  ['awkward', 'What\'s the most embarrassing nickname you\'ve ever had?', 'Gėdingiausia tavo pravardė?', 57],
  ['awkward', 'What\'s a time you laughed at the worst possible moment?', 'Kada nusijuokei pačiu netinkamiausiu metu?', 71],
  ['awkward', 'What\'s the most awkward thing that\'s happened to you at work?', 'Nejaukiausias nutikimas darbe?', 62],
  ['awkward', 'What\'s a compliment you completely botched the response to?', 'Į kokį komplimentą atsakei visiškai nevykusiai?', 55],
  ['couples', 'What\'s something I do that makes you feel most loved?', 'Ką darau, kas tau leidžia jaustis labiausiai mylimam?', 84],
  ['couples', 'What\'s a moment early on when you knew this was different?', 'Kokia ankstyva akimirka leido suprasti, kad tai kitaip?', 79],
  ['couples', 'What\'s something you\'ve learned about love from being with me?', 'Ko apie meilę išmokai būdamas su manimi?', 76],
  ['couples', 'What\'s a small thing I do that you never get tired of?', 'Kokia mano smulkmena tau niekada nenusibosta?', 70],
  ['couples', 'What\'s a fear you had about relationships that I\'ve helped you let go of?', 'Kokią baimę dėl santykių padėjau tau paleisti?', 73],
  ['couples', 'What\'s something you want us to do together that we haven\'t yet?', 'Ką nori, kad kartu padarytume, ko dar nedarėme?', 65],
  ['couples', 'What\'s a memory of us you replay when you\'re having a hard day?', 'Kokį mūsų prisiminimą prisimeni sunkią dieną?', 81],
  ['couples', 'What\'s something you\'ve never told me but always meant to?', 'Ko man niekada nesakei, nors visada ketinai?', 86],
  ['couples', 'What does a perfect ordinary day with me look like to you?', 'Kaip atrodo tobula eilinė diena su manimi?', 68],
  ['couples', 'What\'s a way I\'ve changed you for the better?', 'Kaip pakeičiau tave į gerą pusę?', 74],
  ['couples', 'What\'s something you appreciate about how we handle disagreements?', 'Ką vertini tame, kaip sprendžiame nesutarimus?', 62],
  ['couples', 'What\'s a dream you have for us five years from now?', 'Kokia tavo svajonė apie mus po penkerių metų?', 71],
  ['couples', 'What\'s the moment you felt most understood by me?', 'Kada jauteisi mano labiausiai suprastas?', 78],
  ['couples', 'What\'s something about our relationship you never want to take for granted?', 'Ko mūsų santykiuose nenori laikyti savaime suprantamu?', 69],
  ['couples', 'What\'s a way you\'d like us to grow together this year?', 'Kaip norėtum, kad šiais metais augtume kartu?', 66],
  ['food', 'What\'s a meal that instantly takes you back to your childhood?', 'Koks patiekalas akimirksniu grąžina į vaikystę?', 64],
  ['food', 'What\'s the best meal you\'ve ever had, and where were you?', 'Geriausias patiekalas, kokį valgei — ir kur tai buvo?', 58],
  ['food', 'What\'s a dish you make when you want to feel taken care of?', 'Ką gamini, kai nori pasijusti prižiūrimas?', 61],
  ['food', 'What\'s a food you hated as a kid that you love now?', 'Kokio maisto nekentei vaikystėje, o dabar mėgsti?', 52],
  ['food', 'What\'s the most adventurous thing you\'ve ever eaten?', 'Drąsiausias dalykas, kurį suvalgei?', 47],
  ['food', 'What\'s a recipe that\'s been passed down in your family?', 'Koks receptas perduodamas tavo šeimoje?', 66],
  ['food', 'What\'s a meal you\'d choose if it were your last?', 'Ką rinktumeisi, jei tai būtų paskutinis valgis?', 55],
  ['food', 'What\'s a food memory tied to someone you love?', 'Koks maisto prisiminimas susijęs su mylimu žmogumi?', 70],
  ['food', 'What\'s the best thing you\'ve ever cooked for someone else?', 'Geriausias dalykas, kurį pagaminai kitam?', 50],
  ['food', 'What\'s a cuisine you\'d eat every day if you could?', 'Kokią virtuvę valgytum kasdien, jei galėtum?', 44],
  ['food', 'What\'s a food you refuse to compromise on the quality of?', 'Kokio maisto kokybės nesutinki aukoti?', 41],
  ['food', 'What\'s the worst meal you\'ve ever eaten, and why did you finish it?', 'Blogiausias valgis — ir kodėl jį suvalgei iki galo?', 57],
  ['food', 'What\'s a smell from a kitchen that instantly makes you feel at home?', 'Koks virtuvės kvapas iškart sukuria namų jausmą?', 62],
  ['food', 'What\'s a food tradition from your family you hope to keep alive?', 'Kokią šeimos maisto tradiciją nori išsaugoti?', 59],
  ['food', 'What\'s a dish you\'re proud you finally learned to cook?', 'Kokį patiekalą didžiuojiesi pagaliau išmokęs gaminti?', 48],
];

const SURFACES = {
  'Warm paper':   { bg: 'oklch(0.90 0.012 85)',  dark: false },
  'Ash grey':     { bg: 'oklch(0.83 0.005 250)', dark: false },
  'Category tint':{ bg: null,                    dark: false },
  'Ink card':     { bg: 'oklch(0.26 0.008 260)', dark: true },
};
const CAT_TINT = { fun:'oklch(0.87 0.035 55)', know:'oklch(0.87 0.035 85)', deep:'oklch(0.87 0.035 300)', team:'oklch(0.87 0.035 155)', spicy:'oklch(0.87 0.035 20)', future:'oklch(0.87 0.035 265)', firsts:'oklch(0.87 0.035 220)', awkward:'oklch(0.87 0.035 35)', couples:'oklch(0.87 0.035 5)', food:'oklch(0.87 0.035 120)' };

const OPT_IN = ['couples', 'spicy'];
const CORE = CATS.filter(c => !OPT_IN.includes(c.id)).map(c => c.id);

const UI = {
  en: { fav:'FAV', stats:'STATS', say:'SAY', categories:'CATEGORIES', shuffle:'SHUFFLE & PLAY',
        favTitle:'FAVORITES', favEmpty:'Nothing kept yet. Heart a card you want to come back to — it lives here for this session.',
        statsTitle:'MOST LOVED', statsNote:'How often each question gets hearted across everyone playing. We keep the good ones, cut the rest.',
        sayTitle:'TELL US', sayNote:'What is missing? What felt flat? Anything you would add?', send:'SEND', thanks:'Got it. Thank you.',
        tapHint:'TAP OR SWIPE', introLine:'One question at a time. Read it out loud and pass the phone around.', start:'START', all:'ALL',
        tagline:'CONVERSATION CARDS FOR GROUPS', introFoot:'LIVE PROTOTYPE — TAP ANYTHING',
        introHow:'Tap the card or swipe to advance. Like what you want to keep.', introTop:'Top row: categories, favorites, stats, feedback, language.',
        deckMeta:'150 QUESTIONS · 10 CATEGORIES', langLabelHome:'LANGUAGE', loop:'STARTING OVER', shareTitle:'SHARE', shareNote:'Sends the card as an image, with a link back to Trala.la.',
        share:'SHARE CARD', shared:'SHARED ✓', copy:'COPY', copied:'COPIED ✓',
        favShareHint:'Tap ↗ on any card to share it.' },
  lt: { fav:'MĖGST', stats:'STATS', say:'SAKYK', categories:'KATEGORIJOS', shuffle:'MAIŠYTI IR ŽAISTI',
        favTitle:'MĖGSTAMIAUSI', favEmpty:'Kol kas tuščia. Pažymėk širdute kortelę, prie kurios norėsi grįžti — ji liks čia visai sesijai.',
        statsTitle:'LABIAUSIAI PATIKĘ', statsNote:'Kaip dažnai kiekvienas klausimas pažymimas širdute tarp visų žaidžiančiųjų. Gerus paliekam, kitus išmetam.',
        sayTitle:'PASAKYK', sayNote:'Ko trūksta? Kas nuobodu? Ką pridėtum?', send:'SIŲSTI', thanks:'Gavom. Ačiū.',
        tapHint:'BAKST ARBA BRŪKŠT', introLine:'Po vieną klausimą. Perskaityk garsiai ir perduok telefoną ratu.', start:'PRADĖTI', all:'VISOS',
        tagline:'POKALBIŲ KORTELĖS GRUPĖMS', introFoot:'PROTOTIPAS — BAKST BET KUR',
        introHow:'Bakst kortelę arba brūkšt — kita. Pažymėk, ką nori pasilikti.', introTop:'Viršuje: kategorijos, mėgstami, statistika, atsiliepimai, kalba.',
        deckMeta:'150 KLAUSIMŲ · 10 KATEGORIJŲ', langLabelHome:'KALBA', loop:'PRADEDAM IŠ NAUJO', shareTitle:'DALINTIS', shareNote:'Išsiunčia kortelę kaip paveikslėlį su nuoroda į Trala.la.',
        share:'SIŲSTI KORTELĘ', shared:'IŠSIŲSTA ✓', copy:'KOPIJUOTI', copied:'NUKOPIJUOTA ✓',
        favShareHint:'Bakst ↗ ant kortelės, kad pasidalintum.' },
};

// Categories NOT in the default "ALL" deck — they only appear when picked.
export const OPT_IN = ['couples', 'spicy'];
export const CORE = CATS.filter((c) => !OPT_IN.includes(c.id)).map((c) => c.id);

export const CATEGORIES = CATS;
export const QUESTIONS = Q;
export const SURFACE_OPTIONS = SURFACES;
export const TINTS = CAT_TINT;
export const STRINGS = UI;
