// Marketing copy for the landing sections below the game (app/LandingContent.jsx,
// app/LandingFooter.jsx). Kept separate from lib/content.js, which is the game's
// own question/UI-string data. Vibe entries are keyed by the same category ids
// as CATEGORIES in lib/content.js.

export const LANDING = {
  en: {
    kicker: 'TRALALA',
    h2Line1: 'Conversation Cards for',
    h2Line2: 'Friends, Couples & Groups',
    lede: "Some questions are easy icebreakers. Others are the ones you've never said out loud. Pick a deck and start.",
    cta: 'Start a Conversation',
    introFine: "Free to play. No account needed.",
    vibesH2: "Choose your vibe",
    vibes: {
      union: { title: "The Appliance Union: Funny Questions to Ask", blurb: "Your fridge, bed and charger have complaints about you. Silly questions for any group." },
      know: { title: "Know Me: Get to Know You Questions", blurb: "Easy icebreakers for meeting new people, first dates and new friends." },
      night: { title: "3AM: Deep Questions for Late Nights", blurb: "Deep questions to ask friends after midnight: confessions, big ideas and honest talks." },
      reply: { title: "Office: Team Building Questions", blurb: "Funny icebreakers for work: pointless meetings, reply-all disasters and awards for coworkers." },
      spicy: { title: "Spicy Questions (18+)", blurb: "Bold, flirty questions for adults, from mild to no mercy." },
      dnd: { title: "Do Not Disturb: Questions for Introverts", blurb: "Gentle conversation starters about quiet nights in, canceled plans and time alone." },
      firsts: { title: "Firsts: Questions About Memories", blurb: "First jobs, first trips, first heartbreaks: questions that bring the stories back." },
      awkward: { title: "Awkward: Funny Questions to Ask Friends", blurb: "Embarrassing moments and confessions that get the whole group laughing." },
      duo: { title: "Double Trouble: Questions for Couples", blurb: "Fun date night questions: last bites, inside jokes and who apologizes first." },
      door: { title: "The Wrong Door: What If Questions", blurb: "Imaginative what-if questions about mystery doors, other worlds and roads not taken." },
      fries: { title: "Cold Fries: This or That Questions", blurb: "Pineapple on pizza, socks in bed and other would-you-rather debates." },
    },
    aboutH2: "What is Tralala?",
    aboutP1: "Tralala is a free deck of conversation cards for friends, couples, parties and teams. It hands you the next question before the silence gets awkward.",
    aboutP2: "The app shows one question at a time. Read it out loud, pass the phone and see where the talk goes. There are eleven decks: the appliance union, 3AM, Double Trouble (for couples), Office (for work teams), icebreakers, spicy (18+), do not disturb, firsts, awkward, the wrong door and Cold Fries (this or that). You can also play all of them mixed together. Every card is available in six languages, and we keep adding new ones.",
    aboutP3: "No download and no account needed. Tralala runs in your browser on any phone, and you can add it to your home screen like an app. Star a question you like and it stays in Saved, ready to share later.",
    samplesH2: "Sample questions from each deck",
    samplesPlay: "Play this deck",
    faqH2: "Frequently asked questions",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["Is Tralala free?", "Yes. Every deck and every card is free to play, with no account or sign-up."],
      ["How do you play?", "Open Tralala on one phone and pick a deck. Read the question out loud, let everyone answer, then tap the card or press Next and pass the phone on."],
      ["How many people can play?", "As many as you like, from two people on a date night to a big group at a party or a team meeting. You only need one phone."],
      ["What are good questions to get to know someone?", "Start with the Know Me deck: easy get-to-know-you questions for first dates, new friends and new coworkers. For something lighter, try Cold Fries, where everyone just picks a side."],
      ["Which languages is it in?", "English, Lithuanian, German, Spanish, Italian and Polish. You can switch language at any time."],
      ["Do I need to download an app?", "No. Tralala runs in the browser on any phone. On iPhone or Android you can add it to your home screen so it opens like an app."],
      ["Is there an 18+ deck?", "Yes. The Spicy deck is for adults only (18+), and you choose how far it goes: Mild, Spicy or No mercy. Every other deck works for any group."],
    ],
    ctaH2: "Ready to talk?",
    ctaFine: "No account or setup needed.",
    footer1: "Tralala.cards, made for better conversations.",
    footer2: "We only collect anonymous usage data. No accounts, no personal data.",
    footer3: 'By starting, you agree to anonymous usage data being collected.',
  },

  lt: {
    kicker: 'TRALALA',
    h2Line1: 'Pokalbių kortelės',
    h2Line2: 'draugams, poroms ir grupėms',
    lede: "Vieni klausimai lengvi, pažinčiai. Kiti tokie, kurių niekada nesakei garsiai. Pasirink kaladę ir pradėk.",
    cta: 'Pradėti pokalbį',
    introFine: 'Pradėk nemokamai. Paskyra nereikalinga.',
    vibesH2: 'Pasirink savo nuotaiką',
    vibes: {
      union: { title: "Prietaisų profsąjunga: juokingi klausimai", blurb: "Tavo šaldytuvas, lova ir kroviklis turi tau skundų. Linksmi klausimai bet kuriai kompanijai." },
      know: { title: "Pažink mane: klausimai susipažinti", blurb: "Lengvi klausimai naujoms pažintims, pirmam pasimatymui ir naujiems draugams." },
      night: { title: "3AM: gilūs klausimai naktiniams pokalbiams", blurb: "Gilūs klausimai draugams po vidurnakčio: prisipažinimai, didelės idėjos ir atviri pokalbiai." },
      reply: { title: "Ofisas: klausimai komandos formavimui", blurb: "Linksmi klausimai darbui: beprasmiai susirinkimai, „atsakyti visiems“ katastrofos ir apdovanojimai kolegoms." },
      spicy: { title: "Aštrūs klausimai (18+)", blurb: "Drąsūs, flirtuojantys klausimai suaugusiems: nuo švelnių iki be gailesčio." },
      dnd: { title: "Netrukdyti: klausimai intravertams", blurb: "Ramūs pokalbiai apie vakarus namie, atšauktus planus ir laiką sau." },
      firsts: { title: "Pirmi kartai: klausimai apie prisiminimus", blurb: "Pirmas darbas, pirma kelionė, pirma širdgėla: klausimai, kurie prikelia istorijas." },
      awkward: { title: "Nejaukūs: juokingi klausimai draugams", blurb: "Gėdingos akimirkos ir prisipažinimai, iš kurių juokiasi visa kompanija." },
      duo: { title: "Dviese smagiau: klausimai porai", blurb: "Linksmi klausimai pasimatymui: paskutiniai kąsniai, tik jums suprantami juokeliai ir kas atsiprašo pirmiau." },
      door: { title: "Ne tos durys: klausimai „o kas, jeigu…“", blurb: "Vaizduotę žadinantys klausimai apie paslaptingas duris, kitus pasaulius ir nepasirinktus kelius." },
      fries: { title: "Skonio reikalas: klausimai „tai ar tai“", blurb: "Ananasai ant picos, kojinės lovoje ir kiti kasdieniai ginčai, kuriuose reikia pasirinkti pusę." },
    },
    aboutH2: 'Kas yra Tralala?',
    aboutP1: "Tralala yra nemokamas pokalbių kortelių rinkinys draugams, poroms, vakarėliams ir komandoms. Kitas klausimas atsiranda anksčiau, nei spėja stoti nejauki tyla.",
    aboutP2: "Programėlė rodo po vieną klausimą. Perskaityk jį garsiai, perduok telefoną ir pažiūrėk, kur nuves pokalbis. Kaladžių yra vienuolika: prietaisų profsąjunga, 3AM, dviese smagiau (poroms), Ofisas (komandoms), pažinties, aštrūs (18+), netrukdyti, pirmi kartai, nejaukūs, ne tos durys ir skonio reikalas (tai ar tai). Galima žaisti ir visas kartu. Visi klausimai yra šešiomis kalbomis, o naujų vis pridedame.",
    aboutP3: "Nieko atsisiųsti ir registruotis nereikia. Tralala veikia naršyklėje, bet kuriame telefone, o jei nori, gali ją įsidėti į pradžios ekraną kaip programėlę. Patikusį klausimą pažymėk žvaigždute: jis liks skiltyje „Išsaugoti“, ir vėliau galėsi juo pasidalinti.",
    samplesH2: "Klausimų pavyzdžiai iš kiekvienos kaladės",
    samplesPlay: "Žaisti šią kaladę",
    faqH2: "Dažniausi klausimai",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["Ar Tralala nemokama?", "Taip. Visos kaladės ir kortelės nemokamos, be paskyros ir registracijos."],
      ["Kaip žaisti?", "Atsidaryk Tralala viename telefone ir pasirink kaladę. Garsiai perskaityk klausimą, leisk visiems atsakyti, tada bakstelėk kortelę arba „Kita“ ir perduok telefoną toliau."],
      ["Kiek žmonių gali žaisti?", "Kiek tik norite: nuo dviejų per pasimatymą iki didelės kompanijos vakarėlyje ar komandos susitikime. Užtenka vieno telefono."],
      ["Kokie klausimai tinka susipažinti?", "Pradėk nuo kaladės „Pažink mane“: lengvi klausimai pirmam pasimatymui, naujiems draugams ar kolegoms. Jei nori dar lengviau, rinkis „Skonio reikalą“, kur tereikia pasirinkti pusę."],
      ["Kokiomis kalbomis galima žaisti?", "Anglų, lietuvių, vokiečių, ispanų, italų ir lenkų. Kalbą gali pakeisti bet kada."],
      ["Ar reikia atsisiųsti programėlę?", "Ne. Tralala veikia bet kurio telefono naršyklėje. „iPhone“ ar „Android“ telefone ją gali įsidėti į pradžios ekraną, kad atsidarytų kaip programėlė."],
      ["Ar yra kaladė suaugusiems?", "Taip. „Aštrūs“ klausimai skirti tik suaugusiems (18+), o aštrumą renkiesi tu: švelniai, aštriai arba be gailesčio. Visos kitos kaladės tinka bet kuriai kompanijai."],
    ],
    ctaH2: 'Pasiruošęs pokalbiui?',
    ctaFine: "Paskyros ir nustatymų nereikia.",
    footer1: "Tralala.cards, sukurta geresniems pokalbiams.",
    footer2: "Renkame tik anoniminius naudojimo duomenis. Jokių paskyrų, jokių asmens duomenų.",
    footer3: 'Paspaudus „Pradėti“, sutinkama su anoniminių naudojimo duomenų rinkimu.',
  },

  de: {
    kicker: 'TRALALA',
    h2Line1: 'Gesprächskarten für',
    h2Line2: 'Freunde, Paare & Gruppen',
    lede: "Manche Fragen brechen locker das Eis und helfen dir, neue Leute kennenzulernen. Andere hast du noch nie laut ausgesprochen. Wähl ein Deck und leg los.",
    cta: 'Gespräch starten',
    introFine: 'Kostenlos starten. Kein Konto nötig.',
    vibesH2: 'Wähle deinen Vibe',
    vibes: {
      union: { title: "Die Gerätegewerkschaft: lustige Fragen", blurb: "Dein Kühlschrank, dein Bett und dein Ladegerät haben Beschwerden über dich. Lustige Fragen für jede Runde." },
      know: { title: "Kennenlernfragen: neue Leute kennenlernen", blurb: "Lockere Fragen fürs erste Date, neue Freunde oder die WG-Party." },
      night: { title: "3AM: tiefgründige Fragen für die Nacht", blurb: "Tiefgründige Fragen an Freunde nach Mitternacht: Geständnisse, große Ideen und ehrliche Gespräche." },
      reply: { title: "Das Büro: Teambuilding-Fragen", blurb: "Lustige Eisbrecher für die Arbeit: sinnlose Meetings, „Allen antworten“-Pannen und Preise für Kolleg:innen." },
      spicy: { title: "Pikante Fragen (18+)", blurb: "Mutige, flirtende Fragen für Erwachsene, von mild bis gnadenlos." },
      dnd: { title: "Bitte nicht stören: Fragen für Introvertierte", blurb: "Ruhige Gesprächsfragen über Abende zu Hause, abgesagte Pläne und Zeit für dich allein." },
      firsts: { title: "Premieren: Fragen über Erinnerungen", blurb: "Erster Job, erste Reise, erster Liebeskummer: Fragen, die die Geschichten zurückholen." },
      awkward: { title: "Peinlich: lustige Fragen für Freunde", blurb: "Peinliche Momente und Geständnisse, über die die ganze Runde lacht." },
      duo: { title: "Topf & Deckel: Fragen für Paare", blurb: "Lustige Fragen fürs Date: letzte Bissen, Insider-Witze und wer sich zuerst entschuldigt." },
      door: { title: "Die falsche Tür: Was-wäre-wenn-Fragen", blurb: "Fantasievolle Was-wäre-wenn-Fragen über geheimnisvolle Türen, andere Welten und nicht gegangene Wege." },
      fries: { title: "Glaubensfragen: Dies-oder-das-Fragen", blurb: "Ananas auf Pizza, Socken im Bett und andere Alltagsdebatten, bei denen du dich entscheiden musst." },
    },
    aboutH2: 'Was ist Tralala?',
    aboutP1: "Tralala ist ein kostenloses Set Gesprächskarten für Freunde, Paare, Partys und Teams. Es liefert dir die nächste Frage, bevor die Stille unangenehm wird.",
    aboutP2: "Die App zeigt eine Frage nach der anderen. Lies sie laut vor, gib das Handy weiter und schau, wohin das Gespräch führt. Es gibt elf Decks: Gerätegewerkschaft, 3AM, Topf & Deckel (für Paare), Das Büro (fürs Team), Kennenlernen, pikant (18+), Bitte nicht stören, Premieren, peinlich, die falsche Tür und Glaubensfragen (dies oder das). Du kannst auch alle gemischt spielen. Jede Karte gibt es in sechs Sprachen, und wir fügen laufend neue hinzu.",
    aboutP3: "Kein Download, kein Konto. Tralala läuft im Browser auf jedem Handy, und du kannst es wie eine App auf deinen Home-Bildschirm legen. Markier eine Frage mit einem Stern, dann bleibt sie unter „Gespeichert“ und du kannst sie später teilen.",
    samplesH2: "Beispielfragen aus jedem Deck",
    samplesPlay: "Dieses Deck spielen",
    faqH2: "Häufige Fragen",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["Ist Tralala kostenlos?", "Ja. Alle Decks und Karten sind kostenlos, ohne Konto und ohne Anmeldung."],
      ["Wie spielt man?", "Öffne Tralala auf einem Handy und wähle ein Deck. Lies die Frage laut vor, lass alle antworten, tippe dann auf die Karte oder auf „Weiter“ und gib das Handy weiter."],
      ["Wie viele können mitspielen?", "So viele ihr wollt: vom Date zu zweit bis zur großen Runde auf einer Party oder im Team-Meeting. Ihr braucht nur ein Handy."],
      ["Kann ich mit Tralala neue Leute kennenlernen?", "Ja. Das Deck „Kennenlernen“ hat lockere Fragen für neue Gesichter, zum Beispiel beim ersten Date, in einer neuen WG oder bei einem Treffen mit Unbekannten. Ein Handy reicht, und alle kommen ins Gespräch."],
      ["In welchen Sprachen gibt es Tralala?", "Englisch, Litauisch, Deutsch, Spanisch, Italienisch und Polnisch. Du kannst die Sprache jederzeit wechseln."],
      ["Muss ich eine App herunterladen?", "Nein. Tralala läuft im Browser auf jedem Handy. Auf dem iPhone oder Android-Handy kannst du es auf den Home-Bildschirm legen, dann öffnet es sich wie eine App."],
      ["Gibt es ein Deck ab 18?", "Ja. Das Deck „Pikant“ ist nur für Erwachsene (18+), und du bestimmst, wie weit es geht: Mild, Scharf oder Gnadenlos. Alle anderen Decks passen für jede Runde."],
    ],
    ctaH2: 'Bereit zu reden?',
    ctaFine: "Kein Konto, keine Einrichtung nötig.",
    footer1: "Tralala.cards, gemacht für bessere Gespräche.",
    footer2: "Wir erheben nur anonyme Nutzungsdaten. Keine Konten, keine personenbezogenen Daten.",
    footer3: 'Mit dem Start stimmst du der Erhebung anonymer Nutzungsdaten zu.',
  },

  es: {
    kicker: 'TRALALA',
    h2Line1: 'Cartas de conversación para',
    h2Line2: 'amigos, parejas y grupos',
    lede: "Hay preguntas fáciles para romper el hielo. Otras son las que nunca has dicho en voz alta. Elige una baraja y empieza.",
    cta: 'Iniciar una conversación',
    introFine: 'Empieza gratis. No necesitas cuenta.',
    vibesH2: 'Elige tu vibra',
    vibes: {
      union: { title: "El Sindicato de Electrodomésticos: preguntas divertidas", blurb: "Tu nevera, tu cama y tu cargador tienen quejas sobre ti. Preguntas divertidas para cualquier grupo." },
      know: { title: "Conóceme: preguntas para conocer a alguien", blurb: "Preguntas fáciles para conocer gente nueva, una primera cita o nuevos amigos." },
      night: { title: "3AM: preguntas profundas para la madrugada", blurb: "Preguntas profundas para amigos después de medianoche: confesiones, grandes ideas y charlas sinceras." },
      reply: { title: "La oficina: preguntas para equipos de trabajo", blurb: "Rompehielos divertidos para el trabajo: reuniones inútiles, desastres de «responder a todos» y premios para compañeros." },
      spicy: { title: "Preguntas picantes (18+)", blurb: "Preguntas atrevidas y coquetas para adultos, de suave a sin piedad." },
      dnd: { title: "No molestar: preguntas para introvertidos", blurb: "Charlas tranquilas sobre noches en casa, planes cancelados y tiempo a solas." },
      firsts: { title: "Primeras veces: preguntas sobre recuerdos", blurb: "Primer trabajo, primer viaje, primer desamor: preguntas que traen de vuelta las historias." },
      awkward: { title: "Incómodas: preguntas divertidas para amigos", blurb: "Momentos vergonzosos y confesiones que hacen reír a todo el grupo." },
      duo: { title: "Tal para cual: preguntas para parejas", blurb: "Preguntas divertidas para una cita: últimos bocados, bromas internas y quién pide perdón primero." },
      door: { title: "La puerta equivocada: preguntas «¿y si…?»", blurb: "Preguntas «¿y si…?» sobre puertas misteriosas, otros mundos y caminos que no tomaste." },
      fries: { title: "Debates de sobremesa: preguntas «esto o aquello»", blurb: "Piña en la pizza, calcetines en la cama y otros debates del día a día en los que hay que elegir bando." },
    },
    aboutH2: '¿Qué es Tralala?',
    aboutP1: "Tralala es una baraja gratuita de cartas de conversación para amigos, parejas, fiestas y equipos. Te da la siguiente pregunta antes de que el silencio se vuelva incómodo.",
    aboutP2: "La app muestra una pregunta cada vez. Léela en voz alta, pasa el teléfono y mira adónde va la conversación. Hay once barajas: el sindicato de electrodomésticos, 3AM, tal para cual (para parejas), la oficina (para equipos), para romper el hielo, picantes (18+), no molestar, primeras veces, incómodas, la puerta equivocada y debates de sobremesa (esto o aquello). También puedes jugarlas todas mezcladas. Todas las cartas están en seis idiomas y seguimos añadiendo nuevas.",
    aboutP3: "Sin descargas ni cuentas. Tralala funciona en el navegador de cualquier teléfono y puedes añadirla a tu pantalla de inicio como una app. Marca con una estrella la pregunta que te guste y se quedará en Guardadas, lista para compartir después.",
    samplesH2: "Preguntas de ejemplo de cada baraja",
    samplesPlay: "Jugar esta baraja",
    faqH2: "Preguntas frecuentes",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["¿Tralala es gratis?", "Sí. Todas las barajas y cartas son gratis, sin cuenta ni registro."],
      ["¿Cómo se juega?", "Abre Tralala en un móvil y elige una baraja. Lee la pregunta en voz alta, deja que todos respondan y luego toca la carta o «Siguiente» y pasa el móvil."],
      ["¿Cuántas personas pueden jugar?", "Las que queráis: desde dos en una cita hasta un grupo grande en una fiesta o una reunión de equipo. Solo necesitáis un móvil."],
      ["¿Qué preguntas sirven para conocer a alguien?", "Empieza por la baraja «Conóceme»: preguntas fáciles para una primera cita, nuevos amigos o compañeros nuevos. Si buscas algo más ligero, prueba «Debates de sobremesa», donde solo hay que elegir bando."],
      ["¿En qué idiomas está?", "Inglés, lituano, alemán, español, italiano y polaco. Puedes cambiar de idioma cuando quieras."],
      ["¿Hay que descargar una app?", "No. Tralala funciona en el navegador de cualquier teléfono. En iPhone o Android puedes añadirla a la pantalla de inicio y se abrirá como una app."],
      ["¿Hay una baraja para mayores de 18?", "Sí. La baraja «Picantes» es solo para adultos (18+) y tú eliges hasta dónde llega: Suave, Picante o Sin piedad. Todas las demás barajas sirven para cualquier grupo."],
    ],
    ctaH2: '¿Listo para hablar?',
    ctaFine: "Sin cuenta ni configuración.",
    footer1: "Tralala.cards, hecho para mejores conversaciones.",
    footer2: "Solo recogemos datos de uso anónimos. Sin cuentas ni datos personales.",
    footer3: 'Al empezar, aceptas la recopilación de datos de uso anónimos.',
  },

  it: {
    kicker: 'TRALALA',
    h2Line1: 'Carte per conversazioni con',
    h2Line2: 'amici, coppie e gruppi',
    lede: "Alcune domande rompono il ghiaccio con leggerezza. Altre sono quelle che non hai mai detto ad alta voce. Scegli un mazzo e inizia.",
    cta: 'Inizia una conversazione',
    introFine: 'Inizia gratis. Nessun account necessario.',
    vibesH2: 'Scegli il tuo mood',
    vibes: {
      union: { title: "Il Sindacato degli Elettrodomestici: domande divertenti", blurb: "Il tuo frigo, il tuo letto e il tuo caricabatterie hanno qualcosa da ridire su di te. Domande divertenti per ogni gruppo." },
      know: { title: "Conoscimi: domande per conoscersi", blurb: "Domande facili per conoscere persone nuove, per un primo appuntamento o nuovi amici." },
      night: { title: "3AM: domande profonde per la notte", blurb: "Domande profonde da fare agli amici dopo mezzanotte: confessioni, grandi idee e discorsi sinceri." },
      reply: { title: "L'ufficio: domande per il team building", blurb: "Rompighiaccio divertenti per il lavoro: riunioni inutili, disastri da «rispondi a tutti» e premi per i colleghi." },
      spicy: { title: "Domande piccanti (18+)", blurb: "Domande audaci e maliziose per adulti, da leggere a senza pietà." },
      dnd: { title: "Non disturbare: domande per introversi", blurb: "Chiacchiere tranquille su serate a casa, impegni annullati e tempo tutto per te." },
      firsts: { title: "Prime volte: domande sui ricordi", blurb: "Primo lavoro, primo viaggio, primo cuore spezzato: domande che riportano a galla le storie." },
      awkward: { title: "Imbarazzanti: domande divertenti per amici", blurb: "Momenti imbarazzanti e confessioni che fanno ridere tutto il gruppo." },
      duo: { title: "Anime gemelle: domande per coppie", blurb: "Domande divertenti per un appuntamento: ultimi bocconi, battute tra voi e chi chiede scusa per primo." },
      door: { title: "La porta sbagliata: domande «e se…?»", blurb: "Domande «e se…?» su porte misteriose, altri mondi e strade che non hai preso." },
      fries: { title: "Discorsi da bar: domande «questo o quello»", blurb: "Ananas sulla pizza, calzini a letto e altri dibattiti quotidiani in cui bisogna scegliere da che parte stare." },
    },
    aboutH2: "Cos'è Tralala?",
    aboutP1: "Tralala è un mazzo gratuito di carte per conversazioni tra amici, coppie, feste e team. Ti dà la prossima domanda prima che il silenzio diventi imbarazzante.",
    aboutP2: "L'app mostra una domanda alla volta. Leggila ad alta voce, passa il telefono e guarda dove va la conversazione. Ci sono undici mazzi: il sindacato degli elettrodomestici, 3AM, anime gemelle (per coppie), l'ufficio (per il team), per conoscersi, piccanti (18+), non disturbare, prime volte, imbarazzanti, la porta sbagliata e discorsi da bar (questo o quello). Puoi anche giocarli tutti insieme. Ogni carta è disponibile in sei lingue e ne aggiungiamo sempre di nuove.",
    aboutP3: "Niente download e nessun account. Tralala funziona nel browser di qualsiasi telefono e puoi aggiungerla alla schermata Home come un'app. Segna con una stella la domanda che ti piace: resta tra le Salvate, pronta da condividere più tardi.",
    samplesH2: "Domande di esempio da ogni mazzo",
    samplesPlay: "Gioca questo mazzo",
    faqH2: "Domande frequenti",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["Tralala è gratis?", "Sì. Tutti i mazzi e tutte le carte sono gratis, senza account e senza registrazione."],
      ["Come si gioca?", "Apri Tralala su un telefono e scegli un mazzo. Leggi la domanda ad alta voce, lascia rispondere tutti, poi tocca la carta o «Avanti» e passa il telefono."],
      ["Quante persone possono giocare?", "Quante volete: da due a un appuntamento fino a un gruppo numeroso a una festa o a una riunione di team. Basta un telefono."],
      ["Quali domande fare per conoscere qualcuno?", "Inizia dal mazzo «Conoscimi»: domande semplici per un primo appuntamento, nuovi amici o nuovi colleghi. Per qualcosa di più leggero, prova «Discorsi da bar», dove basta scegliere da che parte stare."],
      ["In quali lingue è disponibile?", "Inglese, lituano, tedesco, spagnolo, italiano e polacco. Puoi cambiare lingua quando vuoi."],
      ["Devo scaricare un'app?", "No. Tralala funziona nel browser di qualsiasi telefono. Su iPhone o Android puoi aggiungerla alla schermata Home e si aprirà come un'app."],
      ["C'è un mazzo per adulti?", "Sì. Il mazzo «Piccanti» è solo per adulti (18+) e scegli tu fin dove arrivare: Leggero, Piccante o Senza pietà. Tutti gli altri mazzi vanno bene per qualsiasi gruppo."],
    ],
    ctaH2: 'Pronto a parlare?',
    ctaFine: "Nessun account né configurazione.",
    footer1: "Tralala.cards, pensato per conversazioni migliori.",
    footer2: "Raccogliamo solo dati di utilizzo anonimi. Nessun account, nessun dato personale.",
    footer3: 'Iniziando, accetti la raccolta di dati di utilizzo anonimi.',
  },

  pl: {
    kicker: 'TRALALA',
    h2Line1: 'Karty do rozmów dla',
    h2Line2: 'przyjaciół, par i grup',
    lede: "Niektóre pytania lekko przełamują lody. Inne to te, których nigdy nie powiedziałeś na głos. Wybierz talię i zaczynaj.",
    cta: 'Rozpocznij rozmowę',
    introFine: 'Zacznij za darmo. Konto niepotrzebne.',
    vibesH2: 'Wybierz swój klimat',
    vibes: {
      union: { title: "Związek Zawodowy AGD: zabawne pytania", blurb: "Twoja lodówka, łóżko i ładowarka mają na ciebie skargi. Zabawne pytania dla każdej grupy." },
      know: { title: "Poznaj mnie: pytania na zapoznanie się", blurb: "Łatwe pytania, żeby poznać nowe osoby: na pierwszą randkę albo z nowymi znajomymi." },
      night: { title: "3AM: głębokie pytania na nocne rozmowy", blurb: "Głębokie pytania do przyjaciół po północy: wyznania, wielkie pomysły i szczere rozmowy." },
      reply: { title: "Biuro: pytania na integrację zespołu", blurb: "Zabawne pytania na przełamanie lodów w pracy: bezsensowne spotkania, wpadki z „odpowiedz wszystkim” i nagrody dla współpracowników." },
      spicy: { title: "Pikantne pytania (18+)", blurb: "Odważne, flirciarskie pytania dla dorosłych, od łagodnych po bez litości." },
      dnd: { title: "Nie przeszkadzać: pytania dla introwertyków", blurb: "Spokojne rozmowy o wieczorach w domu, odwołanych planach i czasie tylko dla siebie." },
      firsts: { title: "Pierwszy raz: pytania o wspomnienia", blurb: "Pierwsza praca, pierwsza podróż, pierwsze złamane serce: pytania, które przywołują historie." },
      awkward: { title: "Niezręczne: zabawne pytania dla przyjaciół", blurb: "Wstydliwe chwile i wyznania, przy których śmieje się cała grupa." },
      duo: { title: "Jak w korcu maku: pytania dla par", blurb: "Zabawne pytania na randkę: ostatnie kęsy, wspólne żarty i kto pierwszy przeprasza." },
      door: { title: "Nie te drzwi: pytania „co by było, gdyby”", blurb: "Pytania „co by było, gdyby” o tajemniczych drzwiach, innych światach i drogach, których nie wybrałeś/aś." },
      fries: { title: "Kłótnie o pietruszkę: pytania „to czy to”", blurb: "Ananas na pizzy, skarpetki w łóżku i inne codzienne spory, w których trzeba wybrać stronę." },
    },
    aboutH2: 'Czym jest Tralala?',
    aboutP1: "Tralala to darmowy zestaw kart do rozmów dla przyjaciół, par, imprez i zespołów. Podaje kolejne pytanie, zanim zapadnie niezręczna cisza.",
    aboutP2: "Aplikacja pokazuje jedno pytanie naraz. Przeczytaj je na głos, podaj telefon dalej i zobacz, dokąd zaprowadzi was rozmowa. Jest jedenaście talii: związek zawodowy AGD, 3AM, jak w korcu maku (dla par), biuro (dla zespołów), na przełamanie lodów, pikantne (18+), nie przeszkadzać, pierwsze razy, niezręczne, nie te drzwi i kłótnie o pietruszkę (to czy to). Możesz też grać wszystkimi naraz. Każda karta jest w sześciu językach, a nowe wciąż dodajemy.",
    aboutP3: "Bez pobierania i bez konta. Tralala działa w przeglądarce na każdym telefonie, a jeśli chcesz, dodasz ją do ekranu początkowego jak aplikację. Oznacz gwiazdką pytanie, które ci się podoba, a zostanie w Zapisanych, gotowe do udostępnienia.",
    samplesH2: "Przykładowe pytania z każdej talii",
    samplesPlay: "Zagraj tą talią",
    faqH2: "Najczęstsze pytania",
    // Plain facts only; also published as FAQPage structured data (lib/seo.js).
    faq: [
      ["Czy Tralala jest darmowa?", "Tak. Wszystkie talie i karty są darmowe, bez konta i rejestracji."],
      ["Jak się gra?", "Otwórz Tralalę na jednym telefonie i wybierz talię. Przeczytaj pytanie na głos, niech wszyscy odpowiedzą, potem stuknij kartę albo „Dalej” i podaj telefon dalej."],
      ["Ile osób może grać?", "Ile chcecie: od dwóch osób na randce po dużą grupę na imprezie albo spotkaniu zespołu. Wystarczy jeden telefon."],
      ["Jakie pytania zadać, żeby kogoś poznać?", "Zacznij od talii „Poznaj mnie”: łatwe pytania na pierwszą randkę, dla nowych znajomych albo nowych osób w pracy. Jeśli chcesz czegoś lżejszego, wybierz „Kłótnie o pietruszkę”, gdzie wystarczy wybrać stronę."],
      ["W jakich językach jest dostępna?", "Angielski, litewski, niemiecki, hiszpański, włoski i polski. Język możesz zmienić w każdej chwili."],
      ["Czy trzeba pobierać aplikację?", "Nie. Tralala działa w przeglądarce na każdym telefonie. Na iPhonie lub Androidzie możesz dodać ją do ekranu początkowego, żeby otwierała się jak aplikacja."],
      ["Czy jest talia dla dorosłych?", "Tak. Talia „Pikantne” jest tylko dla dorosłych (18+), a poziom wybierasz ty: Łagodnie, Pikantnie albo Bez litości. Pozostałe talie pasują do każdej grupy."],
    ],
    ctaH2: 'Gotowy na rozmowę?',
    ctaFine: "Bez konta i konfiguracji.",
    footer1: "Tralala.cards, stworzone dla lepszych rozmów.",
    footer2: "Zbieramy tylko anonimowe dane o użytkowaniu. Bez kont i danych osobowych.",
    footer3: 'Rozpoczynając, zgadzasz się na zbieranie anonimowych danych o użytkowaniu.',
  },
};
